ucbpylegroup/RQpy

rqpy/io/_io.py, rqpy/process/_process_rq.py
Processing and I/O functions now support loading traces from different detectors when using `filetype=="mid.gz"`. 
This affects functions in the `_io.py` and `_process_rq.py` files. Written such that it should be backwards compatible.
=> Support loading traces from different detectors

rqpy/plotting/_plotting.py
Before, if xlims was not specified, and the bins parameter was, then the bin widths for the different cuts would be different. This fix makes it so that the bin widths are the same.
=> xlims in rqpy.hist is set via the range of the plotted data to avoid bin sizing issues

rqpy/io/_io.py, rqpy/plotting/_plotting.py, rqpy/process/_process_iv_didv.py, rqpy/process/_trigger.py
The changes are as follows:
1. Make the documentation and optional arguments for various functions follow the proper conventions
2. Update `get_traces_npz` documentation (issue #13)
3. Add `lgcreturndict` optional argument to `get_traces_midgz` so that the user can choose not to return the dictionary with all of the event information if it is unnecessary.
4. Take out a couple imports that are unused
=> Documentation updates, added functionality to get_traces_midgz

rqpy/io/_io.py, rqpy/process/_process_rq.py
`get_traces_midgz` now defaults to `lgcskip_empty=True` and `lgcreturndict=False` as requested by Issue #19.
=> change get_traces_midgz defaults 

rqpy/process/_process_rq.py
New RQs are added as options for processing. There is now support for the baseline-corrected optimum filter in QETpy, and the smoothed PSD versions of the RQs are also supported.
We have also switched to using the `qetpy.OptimumFilter` class for most of the RQ calculations, which should help speed up processing by reducing the amount of FFTs.
=> Adding the baseline and the smoothed PSD RQs to processing, switch to using OptimumFilter class for most RQs

rqpy/plotting/_plotting.py
I've changed the `rqpy.hist` and `rqpy.scatter` functions to be able to plot any number of cuts that are applied sequentially. The total cut efficiency is no longer calculated, but the efficiency of each cut is. 
This is in response to issue #24.
=> hist() and scatter() now support arbitrary numbers of cuts for plotting

rqpy/process/_process_rq.py
The changes in this pull request include:
1. Updates to the `SetupRQ` docstring
2. In the adjust methods, `lgcrun` and `lgcrun_smooth` can now be inputted as lists of bool in order to calculate RQs only for specific channels.
3. Added the ability for truncating the traces when calculating RQs, as requested in Issue #37.
4. Added method (`SetupRQ._check_of()`) check for if any OFs will be calculated, to avoid initializing the `qetpy.OptimumFilter` class unnecessarily.
5. Added `SetupRQ._check_arg_length()` for checking if parameters are scalar and if they are the correct length.
6. Added support for constrained pulse direction, as requested in Issue #34.
7. Changed some default parameters in `SetupRQ` to be trace length agnostic.
I created the `enhancement/energy_absorbed_rq` branch off of …
=> Changed SetupRQ options, added new RQs

rqpy/process/_process_rq.py
The low frequency chi^2 was only calculated for the optimum filter RQs that did not have pulse direction constraints. I've added the necessary code such that it is now calculated for the pulse direction constrained as well.
=> Low frequency chi^2 now calculated for pulse direction constrained RQs

rqpy/process/_process_rq.py
Now that QETpy has `qetpy.utils.energy_absorbed` via https://github.com/ucbpylegroup/QETpy/pull/30, I have added the Energy Absorbed RQ. 
This in response to Issue #36.
=> Add Energy Absorbed RQ

rqpy/core/_cut.py
Fixed `rqpy.binnedcut` so that a `RuntimeError` won't break the function. Also made it so the `min_samples` argument can be set to any value. Added an option to return the parameters of the fitted, user-defined model.
=> rqpy.binnedcut fixes

rqpy/core/_cut.py, rqpy/plotting/_plotting.py
`rqpy.binnedcut` now always outputs the cut and an object that contains the fitted parameters and the function that the cut boundary was specified by.
=> Changed rqpy.binnedcut output

rqpy/core/_cut.py, rqpy/plotting/_plotting.py
Some changes to `rqpy.passageplot` and `rqpy.passage_fraction`.
1. `rqpy.passage_fraction` outputs bin edges instead of bin centers, no longer will divide by zero
2. `rqpy.passageplot` makes better looking histograms and the bin sizes are now the same for successive cuts
=> Updates to rqpy.passageplot and rqpy.passage_fraction

rqpy/core/_pulse.py
I replaced the function `rqpy.ds_trunc` with an improved function, which was renamed to `rqpy.downsample_truncate`. The function now has optional arguments for calculating downsampled PSDs or templates, whereas it was not optional before.
=> Replaced ds_trunc with improved function downsample_truncate

rqpy/process/_process_rq.py
I've added options for calculating the nonlinear OF RQs to `rqpy.process.rq` and `rqpy.process.SetupRQ`. So, we now have the ability to fit the OF amplitude, time shift, rise time, and fall time of a pulse. Note that this option should only be used if the code is running on a supercomputer, as the processing time is quite slow.
This was done in response to Issue #40.
=> Added 2-pole nonlinear OF RQs

rqpy/io/_load.py, rqpy/sim/_pulse_sim.py
Fixed some bugs in the pulse sim, as well as refactored a little bit.
Some changes:
- the cut is now correctly applied to the simulated data
- removed unnecessary `evtnums` and `seriesnums` parameters
- fixed file opening in `getrandevents` for `npz` files.
=> Fixed bugs in Pulse Sim

rqpy/io/_load.py, rqpy/io/_save.py, rqpy/sim/_pulse_sim.py
Added some improvements and a nice class for helping with the use of `rqpy.sim.buildfakepulses`.
- Arbitrary number of templates is now supported, refactored the code to do this
- `rqpy.sim.PulseSim` was added, which is a helper class for running the simulation (but optional, can still use `buildfakepulses`)
- Removed `savefilename` as an argument in the simulation, it is not automatically set
- Truth data saving with `npz` files is now supported for arbitrary numbers of templates
The first and last bullets deal with the re-opened Issue #53.
=> Improvements to the Pulse Simulation

.pre-commit-config.yaml, rqpy/__init__.py, rqpy/_globals.py, rqpy/process/_process_rq.py, rqpy/sim/__init__.py, rqpy/sim/_trig_sim.py
The branch `feature/trigsim` is in a good state to merge to master.
- Added `rqpy.sim.TrigSim`, which is a wrapper around the `trigsim` package developed by Jon Wilson
- Added the trigger simulation amplitude to the RQ processing
- Added a pre-commit yaml file for fun
- Checks for having the `trigsim` package installed
Should be good to go! May make small changes somewhere down the line, but it does its job.
In response to Issue #61.
=> Add the Trigger Simulation for mid.gz files

rqpy/plotting/_plotting.py
In response to Issues #70 and #71. Adds the `cmap` optional argument to `rqpy.densityplot`, as well as fixes the `lgclognorm` argument so that it actually does something.
=> Add cmap option and fix lgclognorm in rqpy.densityplot

rqpy/process/_process_rq.py
In PR https://github.com/ucbpylegroup/QETpy/pull/48, `qetpy.OFnonlin.fit_falltimes` returns a different number of arguments. I've changed the processing so that it is compatible with either version of QETpy.
This is in response to Issue #67, but does not deal with Issue #58.
=> Update RQ processing to make compatible with latest QETpy commits

rqpy/core/_iv_didv_tools.py
I've switched the order of the priors fit and the non-priors fit in the `rqpy.IVanalysis`. This was done to have the priors fit use the non-priors fit's values as the guesses. The reason being that the non-priors fit tends to have a better fit to the time shift value, so the non-priors fit should use the same time shift value as the guess. This helps make sure the priors and non-priors fits will converge, which they should in the case of only passing R_0 and R_\ell.
=> Switch the order of the priors and non-priors dIdV fits in IVanalysis

rqpy/process/_process_iv_didv.py
I've added a small change so that a list of paths to the parent directories of the files to process can be passed to `rqpy.process.process_ivsweep`. This is useful, for example, when running the code on a cluster to process files in parallel.
=> Allow a list of paths to be passed to process_ivsweep

rqpy/core/_cut.py, rqpy/plotting/_plotting.py
I've added the passage fraction error information to `rqpy.passage_fraction`. The standard deviation and the biased estimator are returned, based on the probability distribution in [this paper](https://arxiv.org/pdf/physics/0701199v1.pdf) (see Eq. 12).
There are now four returned values for `rqpy.passage_fraction`, the x values, the measured passage fraction, the biased estimator of the passage fraction, and the standard deviation of the passage fraction (centered on the biased estimator).
I've also updated the `rqpy.passageplot` function to have the option of plotting the 1-sigma error of the passage fraction, via the `showerrorbar` optional argument.
This PR is related to Issue #69.
=> Adding Passage Fraction Error Information

rqpy/sim/_trig_sim.py
I've added to `rqpy.sim` the function `trigger_efficiency`, which is the expected functional form of the trigger efficiency (comes from the convolution of a step function with a Gaussian).
=> Add functional form for trigger efficiency

rqpy/__init__.py, rqpy/limit/__init__.py, rqpy/limit/_limit.py
I've added the OI limit functionality to RQpy. This still requires the user to point the function to the correct path to the Fortran wrapper (`CalcOptLim3_VarNm`) for Steve Yellin's OI code. I didn't add this Fortran code, as it is internal CDMS code.
No internal CDMS code has been directly ported to the code with these commits. I've cited the formulae for much of the functionality (form factors, calculating dRdE, setting up the OI inputs). I believe that this is standalone enough that it's okay to add to the base RQpy functionality.
Related to Issue #82.
=> Adding OI Limit functionality to RQpy

rqpy/process/_process_rq.py, rqpy/sim/_trig_sim.py
I added to `rqpy.sim.TrigSim` a couple of features/changes:
- The trigger time is now returned by `TrigSim.trigger`
- renamed some attributes to create less confusion
- made fir_bits_out and fir_discard_msbs optional arguments, as they may change depending on how the trigger was set up
I also added the ability to pass `templates` and `psds` to `rqpy.process.SetupRQ` as `numpy.ndarray` type variables. This change is also backwards compatible, so the old way of uploading lists will still work.
=> Added the calculation of the Trigger Time to the TrigSim

rqpy/sim/_trig_sim.py
In the previous version of the Trigger Simulation, the L2 trigger used one extra bin than it should have for the valid part of the FIR trace. I added a fix so that we no longer use the extra bin, which gave us 100% matching with data.
=> Add fix for using only the valid region of the FIR trace

rqpy/limit/_limit.py
Added a line so that the `rqpy.limit.optimuminterval` function will sort the inputted `eventenergies`, so that it is not left to the user to do this.
Also fixed the indenting of the `upperlim` docstring.
=> rp.limit.optimuminterval now sorts the eventenergies

rqpy/core/_fitting.py
Fixed the UnboundLocalError coming from line 143 in `rqpy.fit_gauss`. Resolves #103.
=> Fix unboundlocalerror in fit_gauss

rqpy/process/_process_rq.py
I've added more options to the integral RQ, where we can now specify the exact bins before and after the pulse that will be used when subtracting off the offset to better calculate the integral of the pulse.
=> Add more options for the integral RQ

rqpy/limit/_limit.py, rqpy/plotting/_core_plotting.py
Added to `rqpy.plotting.RatePlot.add_drde` the option to plot the smeared dRdE spectrum for a given DM mass/cross section.
Also added the ability to pass the width of the gaussian smearin to `rqpy.limit.optimuminterval`.
=> Add smear option to RatePlot plotting

rqpy/sim/_pulse_sim.py
I've added support for setting variable rise/fall times when using the pulse simulation. The changes are backwards compatible, so the user can still specify a template to use. However, if the rise and fall times are specified, then they supersede the template. As with the amplitudes and time delay values when using the `PulseSim` class, the fall/rise times can be specified exactly or generated from a chosen distribution.
In summary:
- Support for variable rise/fall times for the pulse simulation
- Using [`deepdish`](https://github.com/uchicago-cs/deepdish) to save all the truth information as HDF5 files
- White space fixes
- Docstring fixes
Resolves #66.
=> Add support for changing rise/fall times in pulse simulation

rqpy/limit/_limit.py
This fixes a possible bug in `rqpy.limit.gauss_smear` where the `scipy.signal.convolve` function would induce numerical errors when using `method="fft"`. This would happen because, by default, the function uses `method="auto"`, which will be used for large arrays. In this case, sections of the smeared differential scattering rate that should be zero would no longer be zero, which could result in limits from the `rqpy.limit.optimuminterval` code that are artificially lower.
The fix is to simply specify `method="direct"`, which will give a small performance hit, but correctly deal with this case. This method does the convolution based on array multiplication, i.e. following the definition of convolution.
=> Specify direct convolve method in gauss_smear to avoid numerical errors

rqpy/plotting/_core_plotting.py
I added a small fix that labels how much smearing was doing to dRdE curves in `rqpy.RatePlot`. Makes the labels less confusing.
This is a small enough change that l will merge without waiting for a review... Sorry @cwfink!
=> Add smearing label to Gaussian smeared dRdE curves

rqpy/__init__.py, rqpy/constants/__init__.py, rqpy/constants/_constants.py, rqpy/limit/_limit.py
I've added a submodule for storing frequently used constants, as detailed below. I'm also importing the constants from SciPy for convenience.
- Add the `rqpy.constants` submodule
- Import all constants stored in `scipy.constants` for convenience (in the `__init__.py`)
- Add some frequently used dark matter constants to `_constants.py`
- Change `rqpy/limit/_limit.py` to use this new submodule
=> Add a file for storing constants

rqpy/limit/_limit.py
I've added a couple functions that allow the use of the 2D Gaussian smearing to calculate a limit, as well as some other changes.
- Added the function `drde_max_q` for determining the largest recoil energy for nonzero dRdE given some dark matter mass
- Added the 2D gaussian smearing
- Added an optimum interval wrapper that uses the 2D gaussian smearing (easier to make it a new function)
This 2D Gaussian smearing is meant to correctly take into account correlations between two different energy estimators (e.g. a trigger energy and a reconstructed offline energy) when smearing out the dRdE with a detector resolution.
=> Add 2D Gaussian Smearing to OI Limit Code

rqpy/process/_process_rq.py, rqpy/sim/_trig_sim.py
I've made significant changes to two files.
`rqpy/sim/_trigsim.py`
- Remove trigger threshold method `TrigSim.set_threshold` (user can do the trigger threshold cut offline)
- Add the calculation of the zero time shifting OF amplitude from the FIR filter (for comparison of resolution to other energy estimators), this is returned by `TrigSim.trigger` by default now
`rqpy/process/_process_rq.py`
- Refactor the shifted OF amplitude code to use the optional parameter `windowcenter` in `qetpy.OptimumFilter.ofamp_nodelay`
- Add `windowcenter` to all of the constrained optimum filters (constrained, pileup, baseline), resolves #96 
- Add ability to specify fit used as the non-pileup pulse for the pileup Optimum Filter, resolves #99 
There are also various white space and typo fixes.
=> Calculate no delay amplitude for TrigSim, use windowcenter, update pileup processing

rqpy/process/_process_rq.py
Accidentally forgot to push this commit before requesting the merge for #114. Fixing the arg length check of the `windowcenter` parameter.
=> Add windowcenter to arg length check

rqpy/plotting/_core_plotting.py
Added the function `rqpy.conf_ellipse` to `rqpy/plotting/_core_plotting.py`. Given a mean, covariance matrix, and some confidence level, the function plots the ellipse that contains the amount of data determined by the confidence level, assuming a 2-dimensional normal distribution.
=> Add confidence ellipse plotting 

rqpy/limit/_limit.py
I noticed that the the x values of the `gauss_smear` function were actually incorrectly defined, which would lead to slightly incorrect smeared distributions. Not a huge effect on previous results, but this should be correct now.
=> Fix x values definition in rqpy.limit.gauss_smear

rqpy/limit/_limit.py
I've refactored the code for `rqpy.limit.drde_gauss_smear2d` so that the code does a better job at calculating the smeared dR/dE using a 2D normal distribution. I also fixed a bug that was affecting the smearing. The explicit changes are detailed below.
- remove `rqpy.limit._limit._largest_et` function
- change calculation of the integral bounds in the trigger energy estimator
- make sure that the true energy is integrated in 1 eV bins
- change the heaviside theta function so that it is evaluated as 1 at threshold
- fix bug in the lambda function defining the double integral so that the true energy is inputted correctly
I've done some testing for different levels of smearing and compared to data, and the code seems to be working well.
=> Refactor and improve drde_gauss_smear2d

rqpy/plotting/_core_plotting.py
I added an error check for if the `xvals` and/or `yvals` parameters are within the ranges specified by `xlims` and `ylims`, respectively, to the `rqpy.plotting._core_plotting.densityplot` function. Before this change, the error raised in this case was not very useful and would just cause confusion (as well as being absurdly long).
=> Add error checking to rqpy.densityplot

rqpy/process/_process_rq.py
I've added a new RQ to the processing called `ofamp_shifted` which is the OF amplitude at a bin specified by the user. I also renamed the old `ofamp_shifted` to `ofamp_coinc`, which was the one where we find the OF amplitude at the time of the trigger on other channels.
- New RQ `ofamp_shifted`
- Renamed old `ofamp_shifted` to `ofamp_coinc`
- Refactored parts of the code (moved where some functions are)
=> Add the specific time shift RQ to processing

rqpy/limit/_limit.py
I've made a few changes to the limit code in this PR.
- Switched from using `numpy.cumsum` to `scipy.integrate.cumtrapz` for more accurate integration
- Refactored the smearing distributions to be more readable
- Added an option to subtract out the zero-energy distribution if a more conservative estimate of the dR/dE is desired (the effect may be minimal depending on how much smearing is done).
In the refactor, I added a hidden helper function called `_gauss2d_integrand` for defining the integrand for the 2D smearing. I didn't write a full docstring for this function, based on conversations with @cwfink that we don't need full docstrings for hidden functions. I can add a docstring if someone finds it necessary.
=> Refactor limit code, switch to cumtrapz, add zero-energy subtraction for 2D Gaussian smearing

rqpy/io/_load.py
I added the ability to pass `"all"` to the `ntraces` keyword argument in `rqpy.io.getrandevents`. This will allow the user to have a slightly easier time loading all the traces in a cut. If the cut has greater than 1000 events, a warning is triggered that gently reminds the user to pay attention to their RAM usage. In this PR, I've also carried out some white space fixes that do not change the functionality of the functions in this module.
=> Add ability to pass "all" to getrandevents for easier loading of all traces in a cut

rqpy/process/_process_rq.py
Added an extra feature to RQ processing for the nonlinear OF.
- Can now specify a fixed `taurise` to reduce the number of degrees of freedom, if desired.
- The guesses for the nonlinear OF are now set based on the constrained OF fit (if run)
=> Add ability to fix taurise in nonlinear OF processing

rqpy/core/_cut.py
I've added the ability to include or exclude the upper and lower bounds in `rqpy.inrange`. Before, it was always inclusive of the bounds. However, there may cases where we do not want to do this, so here's that option.
Also removed unnecessary white space in the file.
=> Add option to include/exclude upper and lower bounds in rqpy.inrange

rqpy/core/_cut.py
I refactored the `rqpy.inrange` function that was edited in PR #125, so that it is now one line instead of four different cases in an `if-else` statement.
=> Refactor rqpy.inrange to be one line

requirements.txt, rqpy/sim/__init__.py, rqpy/sim/_random_sampling.py
I've added two functions that use [inverse transform sampling](https://en.wikipedia.org/wiki/Inverse_transform_sampling) to sample data using an arbitrary probability distribution function.
- Added a new file to `rqpy/sim/` called `_random_sampling.py`, which contains the new sampling functions
- Added two functions that use inverse transform sampling
- Added `rqpy.sim.pdf_sampling` which allows the user to define the functional form of a PDF to sample from
- Added `rqpy.sim.sample_from_data`, which allows the user to use measured data to estimate the PDF and the sample from it using either the binned data or a KDE as the estimated PDF
- Updated `requirements.txt` to include `sklearn`, which is used for calculating the KDE of the data in `rqpy.sim.sample_from_data`
=> Add functions for inverse transform sampling

rqpy/plotting/_core_plotting.py
I changed the `rqpy.hist` code so that the bin widths are always the same no matter what was passed for the `nbins` parameter. Previously, if a string was passed, then the first cut/raw data would have different bin widths/edges, while each subsequent cut would have the same bin widths/edges.
Also changed the default `nbins` parameter to `"auto"`, which does a better job than `"sqrt"`.
=> Improve rqpy.hist such that the bin widths/edges are always the same

requirements.txt, rqpy/process/_process_rq.py, rqpy/sim/_trig_sim.py
I've made a few updates to the RQpy trigger simulation code.
- Added the ability to calculate FIR trigger amplitude for a constrained window `rqpy.sim.TrigSim.constrain_trigger`
- Added the ability to use multiple channels in the FIR trigger simulation using the `which_channel` kwarg when initializing `rqpy.sim.TrigSim`
- Fixed minor bugs in processing that could raise errors when calculating low frequency chi-squareds
=> Add a constrained FIR trigger amplitude calculation, allow multichannel trigger simulation

rqpy/plotting/_core_plotting.py
I have made two changes to the core plotting code.
- Fixed a bug in `rqpy.densityplot`
- The function would fail on the creation of the colorbar if an axis `ax` was passed to the function, as the creation of the colorbar is done via the figure `fig`, but `fig = None` when `ax` is passed
- Removed the use of scientific notation by default on the core plotting functions for better readability
=> Fix small bug in density plot, get rid of scientific notation for plotting

rqpy/io/_load.py
we might as well add this small change for Rev E. We should eventually take advantage of new functions in scdmsPyTools for loading detector settings, but for now we should just add this quick fix
=> added lowpassgain as a parameter to get_train_gain

rqpy/plotting/_core_plotting.py
This is just a small change to remove the scientific notation from the x-axis when plotting the passage fraction via `rqpy.passageplot`.
=> Remove scientific notation for x-axis in passageplot

rqpy/sim/_pulse_sim.py
This a small fix where I've made it so we prepend zeros to the saved file name in `_save_truth_info` for the PulseSim. This is just to make it so the number in the saved file name always has 4 numbers and is sorted correctly when listed.
=> Prepend zeros to basedumpnum when saving truth info in PulseSim

requirements.txt, rqpy/__init__.py
Adding an explicit import for seaborn in order to load the various colormaps it adds to matplotlib (since we use icefire as a default for some of our plotting functions, e.g. `rqpy.densityplot`).
=> Add explicit seaborn import for loading icefire cmap

rqpy/core/_cut.py
`rqpy.binnecut` had a bug where if the optional argument `nbins` was set to 1, then an `UnboundLocalError` was raised, as the variable `params` was referenced in the output, but never set in the code.
The simple fix is to set `params = None` for this case.
I also did some changed some white space while fixing this bug.
=> Fix bug in rqpy.binnedcut for the case of nbins=1

rqpy/plotting/_core_plotting.py
In `rqpy.densityplot`, we always had a small issue with trying to set x and y limits that were larger than the range of the data. This is because the plotting function used (`ax.hist2d`) automatically sets the limits based on the range of the data, and we weren't actually using the limits inputted.
I've now passed the limits directly to the `range` kwarg in `ax.hist2d`, so that `xlims` and `ylims` are properly used.
I've also fixed some white space in `_core_plotting.py` as a part of this PR.
=> Improved the use of the xlims and ylims kwargs in rqpy.densityplot

rqpy/plotting/_core_plotting.py
I've added the ability to show the data that was removed by a cut in `rqpy.densityplot`. There are now two more kwargs:
1. `plot_cut_data` - boolean value for whether or not to plot the removed data
2. `basecut` - array of booleans that specifies the previous cut to compare to
There's also a new label `'basecut'` that was added to `labeldict`, which allows the user to name the `basecut` in the legend, if `plot_cut_data` is True.
=> Added ability to show a basecut in rqpy.densityplot

rqpy/plotting/_core_plotting.py
I've added a function to the `_core_plotting.py` file that allows the user to preview how a figure would look, if printed in greyscale. Useful when making plots for publication and checking the colors being used.
=> Add previewgreyscale function

rqpy/plotting/_core_plotting.py
Made the simple change such that `rqpy.hist` defaults to a logarithmic y-scale. Resolves #148.
=> Make rqpy.hist default to log scale

rqpy/io/_load.py
There's a bug where, if the `seriesnumber` is a float, then `rqpy.io.getrandevents` will fail, as it passes an incorrectly formatted string to `getRawEvents` in `scdmsPyTools`. This fix simply ensures that `seriesnumber` is cast as an `int` before being passed to `getRawEvents`.
=> Set seriesnumber to int in rp.io.getrandevents

rqpy/plotting/_core_plotting.py
Passing a path to `rqpy.previewgreyscale` will open the file and show a greyscale version of it.
=> Create greyscale version of an existing file

rqpy/io/_load.py, rqpy/process/_process_rq.py
I've had this on its own branch for a while, but in the RQ processing, I've added a new RQ and a new option to another RQ.
- Added `baseline_post` RQ
- Added option for `ofamp_constrained` to be centered on the FPGA trigger time (simulated)
I recently updated the docstrings, so this should finally be ready to merge to master.
=> Add post baseline and ability to center constrained OF amplitude on the FPGA trigger time

README.md
Updated the README to tell the user to use `pip install .` for the installation step. Recommended by Python and avoids the `clean` step.
See https://github.com/ucbpylegroup/QETpy/issues/92 and https://github.com/ucbpylegroup/QETpy/pull/101 for more info.
=> Update readme to recommend pip install .

rqpy/process/_process_iv_didv.py
Added the underscores needed to access the `qetpy.DIDV` attributes needed in the processing routines for IV/dIdV.
=> Add underscores to be compatible with QETpy DIDV

rqpy/io/_load.py
Added the optional argument `get_charge` to `rqpy.io.get_traces_midgz` to provide users with a function to get the charge channels of a CDMS detector, as requested by @ytcs.
Closes #170.
=> Add get_charge option to get_traces_midgz

pyproject.toml
some combination of pip, numpy, and tensorflow are causing having with rqpy requirnig numpy for the build environment. The proposed change seems to make it a bit more stable
=> fix for numpy being downgraded after build environment

rqpy/process/_process_iv_didv.py
When DIDV data needs to be autoresampled such that an arbitrary number of signal generator periods can fit into a integer number of samples, the IV/dIdV analysis pipeline will fail, as the option to autoresample doesn't exist for the pipeline.
This PR adds the option to autoresample didv data via `autoresample_didv`, and it also ensures that the new digitization rate after the auto resampling is saved.
=> Add option to autoresample DIDV data when processing IV/DIDV sweeps

rqpy/process/_trigger.py
Adding a fix to the continuous trigger code such that the OF does not use the DC (zero-frequency) information.
=> Do not use DC information in continuous triggering
