ucbpylegroup/RQpy

- rqpy/core/_cut.py
The algorithm now finds the value that corresponds to the position that would give the desired cut efficiency, rather than doing it via percentiles. This should give efficiencies that are closer to the desired efficiency. Also cut_eff is now between 0 and 1, and there is a check for if the cut_eff is outside this range.
> change how the percentile is done in baselinecut_tdep

- rqpy/core/__init__.py
- rqpy/core/_fitting.py
- rqpy/core/_rrq.py
- rqpy/utils/_utils.py
added functionality to apply the saturation correction of the measured energy integral to all events.
> Sat energy rrq

- rqpy/core/_cut.py
`rqpy.inrange` now uses a bitwise operator when creating a boolean mask for values that are within the specified range.
> Refactored inrange to use bitwise operand

- rqpy/process/_process_rq.py
I've added three enhancements to the `_process_rq.py` file.
1. Added the maxmin RQ, which calculates the max or min of a trace (this can be constrained over a set range)
2. Add an option to specify where the integral should be evaluated up to.
3. Added the SetupRQ._check_of() method, which checks if an OF should be initialized, so that if we are only calculating baseline, integral, and maxmin, then no unnecessary calculations are done (e.g. FFTs)
This is in response to Issues #32 and #33.
> Added maxmin RQ, ending index for integral, and _check_of method to SetupRQ

- rqpy/core/_cut.py
I've added a feature to `rqpy.binnedcut` such that the function can now fit a functional form to the bins that were created. The functional form is set by the `model` argument, which allows the user three options:
1. `model=None` simply keeps the bin heights as the functional form to cut on
2. `model="linear"` uses `skimage.measure.LinearModelND` to fit a linear model to the function using `skimage.measure.ransac` for outlier removal.
3. `model=function`, where `function` is some user-defined function of the form `f(x, *params)`, allows the user to define a model, which will then be passed to `skimage.measure.ransac`. This requires the user to input a guess of the fit parameters, via the `guess` argument.
I've also suppressed `OptimizeWarning` from appearing when using a user-defined …
> Add fitting functionality to rqpy.binnedcut

- rqpy/core/_iv_didv_tools.py
- rqpy/plotting/_plotting.py
-Address Issue https://github.com/ucbpylegroup/RQpy/issues/78 by correctly scaling R0 and QETbias. Also, added option to plot tau minus on same plot as energy resolution. 
-Fixed Issue https://github.com/ucbpylegroup/RQpy/issues/77 by changing the way the optimum energy is calculated. Also, the qetbias corresponding to the fasted tau minus is now returned. 
- Corrected title error in Issue https://github.com/ucbpylegroup/RQpy/issues/76
- Changed plotting formatting as requested in Issue https://github.com/ucbpylegroup/RQpy/issues/75
> fix optimum energy res calc, and plotting formatting

- rqpy/process/_trigger.py
small additions to resolve issue #65
> add trace scaling option to acquisition functions in trigger

- rqpy/process/_process_rq.py
Added a simple `if` statement to the `_process_rq` function for checking if `readout_inds` says that there are no events to be read out.
Resolves #68.
> Hotfix for rq processing with no readout_inds

- rqpy/process/_process_rq.py
I've added the success/fail of the OFnonlin to the RQs that are saved.
Resolves #58.
> Add success/fail of OFnonlin to RQs

- rqpy/sim/_trig_sim.py
I added to the trigger simulation a hidden method for calculating the conversion factor from the FPGA units to ADC bins, which is useful for comparing the FPGA filter to offline optimum filters. This factor is calculated when the `rqpy.sim.TrigSim` class is initialized, which is then saved as the `convtoadcbins` attribute.
> Add conversion to ADC bins from arbitrary FPGA units

- rqpy/core/_fitting.py
- rqpy/plotting/_fitting_plotting.py
- rqpy/utils/_utils.py
I've added a flag, lgcasymbkg, to the fit_gauss function that allows for fitting of different background levels to the left and right side of the Gaussian.
This new functionality also required adding:
- A plotting function
- The fitting function in utils with a Gaussian and two erf functions
> add Gaussian + asymmetric background fitting

- rqpy/sim/_trig_sim.py
I just want to merge two branches that I'm developing TrigSim updates for, which I'll request to merge to master soon,
> Merge two branches for TrigSim features

- rqpy/process/_process_rq.py
I've added the ability to pass guesses for the rise and fall times to the nonlinear OF, rather than always guessing. 
Also fixed a bug where `_check_arg_length` would raise an error on values set to None.
Refactored the guessing code for nonlinear OF for less repeated code.
> Allow user to directly pass tau fall and tau rise guesses to processing nonlinear OF

- rqpy/limit/_limit.py
I removed some unused lines in the OI code. Also fixed some typos in the dosctrings for the limit code.
> Remove some unused lines in OI code

- rqpy/sim/_sens_est.py
The docstring for `rqpy.sim.trigger_pdf` was out of date, so I've made the small changes to make it match the current version of the function.
> Update docstring for trigger_pdf

- pyproject.toml
- setup.py
As suggested in #154, I've updated the installation files as follows.
- Added the minimal installation requirements to `install_requires` in `setup.py`
- Created a `pyproject.toml` file to specify build dependencies
Resolves #154.
> Update install files

- rqpy/_globals.py
- rqpy/io/_load.py
- rqpy/io/_save.py
- rqpy/process/_process_iv_didv.py
- rqpy/process/_process_rq.py
- rqpy/sim/_pulse_sim.py
- setup.py
Tested import but didn't test any functionality
> use cdms rawio package rather than old scdmsPyTools interface

- rqpy/io/_load.py
Updated the Stanford I/O functions as per Francisco's request. He has tested the functions and confirmed that they work as expected, so I'll merge to master without review.
> Update Stanford I/O Functions

- rqpy/core/_iv_didv_tools.py
> removed diagnostic comments

- rqpy/io/_load.py
I've added the functionality needed for `rqpy.io.getrandevents` to be used on pytesdaq-generated data. Uses the `H5Reader` class in `pytesdaq.io.hdf5` to load traces and select a random selection of events from some specified data quality cut.
> Add pytesdaq filetype to getrandevents
